# Generated by Django 5.1.7 on 2025-03-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalitem",
            name="image",
            field=models.ImageField(
                blank=True,
                default="default_no_image.png",
                null=True,
                upload_to="rental_images/",
            ),
        ),
    ]
