# Generated by Django 5.1.7 on 2025-03-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0002_rentalitem_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentalitem",
            name="image",
            field=models.ImageField(
                blank=True,
                default="default_no_image.png",
                null=True,
                upload_to="media/rental_images/",
            ),
        ),
    ]
