# Generated by Django 5.1.7 on 2025-03-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0004_alter_rentalitem_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalitem",
            name="college",
            field=models.CharField(
                choices=[
                    ("OUTR", "OUTR"),
                    ("Silicon", "Silicon"),
                    ("ITER", "ITER"),
                    ("IIIT BBSR", "IIIT BBSR"),
                    ("IIT BBSR", "IIT BBSR"),
                ],
                default="OUTR",
                max_length=50,
            ),
        ),
    ]
